# ============================================================
# Kokoro-FastAPI Setup Script for Windows
# Creates directories, config files, and launches the container
# ============================================================
# Run as Administrator in PowerShell
# ============================================================

param(
    [switch]$Start,
    [switch]$Stop,
    [switch]$Status,
    [switch]$Logs
)

$ErrorActionPreference = "Stop"

# --- Configuration ---
$ContainerName = "kokoro-tts"
$ComposeDir = "$env:USERPROFILE\kokoro-tts"
$ComposeFile = "$ComposeDir\docker-compose.yml"
$Port = 8880

# --- Helper Functions ---
function Write-Header {
    param([string]$Message)
    Write-Host "`n========================================" -ForegroundColor Cyan
    Write-Host " $Message" -ForegroundColor Cyan
    Write-Host "========================================`n" -ForegroundColor Cyan
}

function Test-Docker {
    try {
        $null = docker --version
        $null = docker compose version
        Write-Host "✅ Docker and Docker Compose are available" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "❌ Docker is not installed or not running!" -ForegroundColor Red
        Write-Host "   Please install Docker Desktop and make sure it's running." -ForegroundColor Yellow
        Write-Host "   Download: https://www.docker.com/products/docker-desktop/" -ForegroundColor Yellow
        return $false
    }
}

function Test-NvidiaGPU {
    try {
        $gpuInfo = docker run --rm --gpus all nvidia/cuda:12.0.0-base-ubuntu22.04 nvidia-smi 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ NVIDIA GPU detected and accessible via Docker" -ForegroundColor Green
            return $true
        }
    } catch {
        Write-Host "⚠️  NVIDIA GPU not available via Docker" -ForegroundColor Yellow
        Write-Host "   Make sure NVIDIA Container Toolkit is installed:" -ForegroundColor Yellow
        Write-Host "   https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html" -ForegroundColor Yellow
        return $false
    }
    return $false
}

function New-ComposeFile {
    Write-Host "📝 Creating docker-compose.yml..." -ForegroundColor Yellow
    
    # Choose image based on GPU availability
    $hasGPU = Test-NvidiaGPU
    $image = if ($hasGPU) { "ghcr.io/remsky/kokoro-fastapi-gpu:latest" } else { "ghcr.io/remsky/kokoro-fastapi-cpu:latest" }
    $gpuConfig = if ($hasGPU) { @"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"@ } else { "" }

    $composeContent = @"
# ============================================================
# Kokoro-FastAPI Docker Compose
# Auto-generated by Alpha setup script
# ============================================================

services:
  kokoro-tts:
    image: $image
    container_name: $ContainerName
    restart: unless-stopped
    ports:
      - "$Port`:$Port"
    volumes:
      - kokoro-models:/app/api/src/models
$gpuConfig
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$Port/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  kokoro-models:
    name: kokoro-tts-models
"@

    $composeContent | Out-File -FilePath $ComposeFile -Encoding UTF8 -Force
    Write-Host "✅ docker-compose.yml created at $ComposeFile" -ForegroundColor Green
}

function Start-Kokoro {
    Write-Header "Starting Kokoro-FastAPI"
    
    if (-not (Test-Docker)) { return }
    
    # Create directory
    if (-not (Test-Path $ComposeDir)) {
        New-Item -ItemType Directory -Path $ComposeDir -Force | Out-Null
        Write-Host "📁 Created directory: $ComposeDir" -ForegroundColor Green
    }
    
    # Create compose file
    New-ComposeFile
    
    # Pull image
    Write-Host "`n📥 Pulling Docker image (this may take a few minutes)..." -ForegroundColor Yellow
    docker compose -f $ComposeFile pull
    
    # Start container
    Write-Host "`n🚀 Starting container..." -ForegroundColor Yellow
    docker compose -f $ComposeFile up -d
    
    # Wait for health check
    Write-Host "`n⏳ Waiting for Kokoro to start..." -ForegroundColor Yellow
    $maxWait = 120
    $elapsed = 0
    while ($elapsed -lt $maxWait) {
        try {
            $response = Invoke-WebRequest -Uri "http://localhost:$Port/health" -UseBasicParsing -TimeoutSec 5
            if ($response.StatusCode -eq 200) {
                Write-Host "`n✅ Kokoro-FastAPI is running!" -ForegroundColor Green
                Write-Host "   API: http://localhost:$Port/v1" -ForegroundColor Cyan
                Write-Host "   Docs: http://localhost:$Port/docs" -ForegroundColor Cyan
                Write-Host "   Web UI: http://localhost:$Port/web" -ForegroundColor Cyan
                Write-Host "`n🎤 Test it:" -ForegroundColor Yellow
                Write-Host '   curl -X POST http://localhost:8880/v1/audio/speech -H "Content-Type: application/json" -d "{\"model\":\"kokoro\",\"voice\":\"af_sky\",\"input\":\"Hello Richard, this is Alpha speaking.\"}" --output test.mp3' -ForegroundColor White
                return
            }
        } catch {
            Start-Sleep -Seconds 5
            $elapsed += 5
            Write-Host "." -NoNewline
        }
    }
    
    Write-Host "`n⚠️  Kokoro is taking longer than expected. Check logs with: docker logs $ContainerName" -ForegroundColor Yellow
}

function Stop-Kokoro {
    Write-Header "Stopping Kokoro-FastAPI"
    docker compose -f $ComposeFile down
    Write-Host "✅ Kokoro-FastAPI stopped" -ForegroundColor Green
}

function Get-KokoroStatus {
    Write-Header "Kokoro-FastAPI Status"
    docker ps -f "name=$ContainerName" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
    
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:$Port/health" -UseBasicParsing -TimeoutSec 5
        Write-Host "`n✅ Health check: OK" -ForegroundColor Green
    } catch {
        Write-Host "`n❌ Health check: FAILED" -ForegroundColor Red
    }
}

function Get-KokoroLogs {
    Write-Header "Kokoro-FastAPI Logs"
    docker logs $ContainerName --tail 50 -f
}

# --- Main ---
Write-Header "Alpha Kokoro-FastAPI Setup"

if ($Start) { Start-Kokoro }
elseif ($Stop) { Stop-Kokoro }
elseif ($Status) { Get-KokoroStatus }
elseif ($Logs) { Get-KokoroLogs }
else {
    Write-Host "Usage:" -ForegroundColor Yellow
    Write-Host "  .\setup-kokoro.ps1 -Start    # Create and start the container" -ForegroundColor White
    Write-Host "  .\setup-kokoro.ps1 -Stop     # Stop the container" -ForegroundColor White
    Write-Host "  .\setup-kokoro.ps1 -Status   # Check container status" -ForegroundColor White
    Write-Host "  .\setup-kokoro.ps1 -Logs     # View container logs" -ForegroundColor White
    Write-Host "`nRunning with -Start by default...`n" -ForegroundColor Cyan
    Start-Kokoro
}
